feeds:
  - https://www.theverge.com/rss/index.xml
  - https://techcrunch.com/tag/artificial-intelligence/feed/
  - https://www.technologyreview.com/feed/
  - https://aws.amazon.com/blogs/aws/feed/
  - https://cloud.google.com/blog/rss/
